spring:
  application:
    name: category-service

#    datasource:
#    url: jdbc:postgresql://category-db-server.postgres.database.azure.com:5432/category-db
#    username: postgres
#    password: Imwinner@1
#    driver-class-name: org.postgresql.Driver

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
        hibernate:
            format_sql: true

server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.priceman.categoryservice: DEBUG  # adjust package name
    com.priceman.productservice: DEBUG   # adjust package name
  file:
    name: logs/app.log

