services:
  product-db:
    image: postgres:16
    container_name: product-db
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: productpass
    ports:
      - "5434:5432"
    volumes:
      - product_data:/var/lib/postgresql/data

  product-service:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: product-service
      ports:
        - "8082:8082"
      depends_on:
        - product-db
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://product-db:5432/productdb
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: productpass
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        SPRING_JPA_SHOW_SQL: true
        SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
        SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
volumes:
  product_data: