spring:
  application:
    name: category-service

  datasource:
    url: jdbc:postgresql://category-db:5432/categorydb
    username: postgres
    password: categorypass



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
